<img src="../images/numpy-anatomy-of-an-array-updated.png"/>

# Why Numpy
+ Fast, 
+ behind the scence it uses C
+ Backbone of many python libraries
+ Vectorization via broadcasting (avoid loops) # when doing large calculations

# Datatypes & Attributes

In [ ]:
arrays , ndim

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])
print(a2)

[[1.  2.  3.3]
 [4.  5.  6.5]]


In [11]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [12]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
a2.shape

(2, 3)

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Attributes

In [22]:
a1.shape , a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [23]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [24]:
# let's create a pandas
import pandas as pd

In [25]:
df = pd.DataFrame(a2)

In [27]:
df.head()

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating numpy array

In [28]:
sample = np.array([1,2,3])

In [30]:
type(sample)

numpy.ndarray

In [32]:
ones = np.ones((2,3)) # am creating an array of ones with 2 dim and 3 rows
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
type(ones) , ones.dtype

(numpy.ndarray, dtype('float64'))

In [35]:
range_a = np.arange(0,10,2)

In [36]:
range_a

array([0, 2, 4, 6, 8])

In [37]:
random_a = np.random.randint(0,10 , size=(3,5))
random_a

array([[1, 8, 3, 2, 6],
       [7, 9, 1, 9, 2],
       [5, 6, 7, 7, 0]])

In [38]:
random_a.size

15

In [39]:
random_a.shape

(3, 5)

In [41]:
random_a2 = np.random.random((5,3))
random_a2

array([[0.04864546, 0.77986581, 0.02794305],
       [0.54449708, 0.97852291, 0.55165317],
       [0.48511618, 0.85989079, 0.46323454],
       [0.31183993, 0.6368314 , 0.72258848],
       [0.02316429, 0.86305135, 0.60274436]])

In [42]:
random_a2.shape

(5, 3)

In [44]:
random_3 = np.random.rand(5,3)
random_3

array([[0.37702604, 0.5139171 , 0.90778276],
       [0.06421886, 0.47427211, 0.08205433],
       [0.52593202, 0.67079417, 0.88674337],
       [0.03724804, 0.43440756, 0.80782806],
       [0.15477242, 0.0642039 , 0.17041405]])

In [ ]:
# psuedo random numbers : Its random but not really random

In [49]:
random_a4 = np.random.randint(10, size=(5,3))
random_a4

array([[0, 8, 8],
       [0, 9, 7],
       [9, 5, 1],
       [1, 0, 1],
       [1, 9, 2]])

In [ ]:
np.random.seed(0)  # allows you to Gen random numbers, so your colleagues get the same results that you had

In [54]:
np.random.seed(0)  # no matter how many time i run this, it wont change, i can also change from 0 to whatever number
random_a5 = np.random.random((5,3))
random_a5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

# Viewing arrays and matrices

### unique
https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [56]:
np.unique(random_a5)

array([0.07103606, 0.38344152, 0.4236548 , 0.43758721, 0.52889492,
       0.54488318, 0.5488135 , 0.56804456, 0.60276338, 0.64589411,
       0.71518937, 0.79172504, 0.891773  , 0.92559664, 0.96366276])

In [58]:
np.unique(random_a4)

array([0, 1, 2, 5, 7, 8, 9])

# Slicing arrays

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [61]:
a2[0]

array([1. , 2. , 3.3])

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [62]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a3.shape

(2, 3, 3)

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [71]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [73]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0]],

        [[4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1]],

        [[7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8]]],


       [[[4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2]],

        [[0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4]],

        [[6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2],
         [3, 2, 0, 8, 8]]]])

In [74]:
a4.shape

(2, 3, 4, 5)

# Get the first 4 numbers of the inner most arrays

In [78]:
a4[:, : ,: , :4]

array([[[[9, 4, 3, 0],
         [5, 0, 2, 3],
         [1, 3, 3, 3],
         [0, 1, 9, 9]],

        [[4, 7, 3, 2],
         [2, 0, 0, 4],
         [5, 6, 8, 4],
         [4, 9, 8, 1]],

        [[7, 9, 9, 3],
         [7, 2, 0, 3],
         [9, 4, 4, 6],
         [4, 3, 4, 4]]],


       [[[4, 3, 7, 5],
         [0, 1, 5, 9],
         [0, 5, 0, 1],
         [4, 2, 0, 3]],

        [[0, 7, 5, 9],
         [2, 7, 2, 9],
         [3, 3, 2, 3],
         [1, 2, 9, 1]],

        [[6, 8, 2, 3],
         [0, 6, 0, 6],
         [3, 8, 8, 8],
         [3, 2, 0, 8]]]])

# Manipulating and Comparing Arrays

In [79]:
a1

array([1, 2, 3])

In [80]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [81]:
a1 + ones

array([2., 3., 4.])

In [82]:
a1 - ones

array([0., 1., 2.])

# Note : This will return an error . See the numpy documentation for Broadcasting or see how to reshape numpy arrays

In [83]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [85]:
a1/ones

array([1., 2., 3.])

# Floor division

In [86]:
a1//ones

array([1., 2., 3.])

In [87]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

# Square root

In [88]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

# Dot product

# Transpose

<img src="../images/numpy-panda.png"/>