# Matrix Multiplication

## Introduction
Understanding matrix operations is very important for a deeper understanding of linear algebra. We know matrices are used throughout the field of machine learning in the description of algorithms and representation of data. In this lesson, we shall discover how to manipulate matrices in Python and Numpy.

## Objectives

You will be able to:

- Compute the dot product for matrices and vectors 
- Calculate a cross product using Numpy 
- Define a cross product

## Definition

Multiplication of two matrices is one of the most crucial operations involving matrices. You can write the matrix product just by placing two or more matrices together, for example, 

> $C = AB$

The standard product of two matrices is not just a matrix containing the element-wise product of the individual elements. This type of operation is a _special case_ and is called the element-wise product, or the **Hadamard product**.

## Hadamard product

Two matrices with the same dimensions can be multiplied together. Such element-wise matrix multiplication is called the Hadamard product. It's not the typical operation meant when referring to matrix multiplication, therefore a different operator is often used, such as a circle $\circ$. 
> $C = A \circ B$

As with element-wise addition and subtraction, element-wise multiplication involves the multiplication of elements from each parent matrix to calculate the values in the new matrix as shown below.

$$ A \circ B = 
   \left[ {\begin{array}{cc}
   A_{1,1} * B_{1,1} & A_{1,2} * B_{1,2}\\
   A_{2,1} * B_{2,1}& A_{2,2} * B_{2,2} \\
   A_{3,1} * B_{3,1} & A_{3,2} * B_{3,2} \\
  \end{array} } \right] 
$$

The Hadamard product can be calculated in Python using the $*$ operator between two NumPy arrays: 

```python
# Element-wise Hadamard product
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
print ('\nHadamard product\n\n', A * B)
```

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3] , [4,5,6]])
print(A)
B = np.array([[1,2,3] , [4,5,6]])
print(B)
print("\nHadamard product\n\n" , A*B)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

Hadamard product

 [[ 1  4  9]
 [16 25 36]]
